function Image_N4 = strong_N4(Image,Mask)

%Implementation of Willmering "strong" 7-step N4 bias correction

N4Path = which('Seg.strong_N4');
idcs = strfind(N4Path,filesep);%determine location of file separators
N4Path = [N4Path(1:idcs(end-1)-1),filesep];%remove file

tmp_dir = 'C:\Users\pniedbalski\OneDrive - University of Kansas Medical Center\Documents\local_tmp';

niftiwrite(Image,fullfile(tmp_dir,'tmp_Im_4_N4'),'Compressed',true);
niftiwrite(Mask,fullfile(tmp_dir,'tmp_Mask_4_N4'),'Compressed',true);

%% Linear
cmd = ['"' fullfile(N4Path,'+Seg','N4BiasFieldCorrection.exe') '" ' ,...
    '-d 3 -i "' fullfile(tmp_dir,'tmp_Im_4_N4.nii.gz') '" ',...
    '-s 1 -w "' fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz') '" ',...
    '-c [25,0] -b [112,1] -t [0.75,0.01,100] ',...
    '-o ["' fullfile(tmp_dir,'tmp_N4_Im.nii.gz"'),',"',fullfile(tmp_dir,'tmp_Bias.nii.gz"]')];
system(cmd)

%% Binomial
cmd = ['"' fullfile(N4Path,'+Seg','N4BiasFieldCorrection.exe') '" ' ,...
    '-d 3 -i "' fullfile(tmp_dir,'tmp_N4_Im.nii.gz') '" ',...
    '-s 1 -w "' fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz') '" ',...
    '-c [25,0] -b [112,2] -t [0.75,0.01,100] ',...
    '-o ["' fullfile(tmp_dir,'tmp_N4_Im.nii.gz"'),',"',fullfile(tmp_dir,'tmp_Bias.nii.gz"]')];
system(cmd)

%% Trinomial
cmd = ['"' fullfile(N4Path,'+Seg','N4BiasFieldCorrection.exe') '" ' ,...
    '-d 3 -i "' fullfile(tmp_dir,'tmp_N4_Im.nii.gz') '" ',...
    '-s 1 -w "' fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz') '" ',...
    '-c [25,0] -b [112,3] -t [0.75,0.01,100] ',...
    '-o ["' fullfile(tmp_dir,'tmp_N4_Im.nii.gz"'),',"',fullfile(tmp_dir,'tmp_Bias.nii.gz"]')];
system(cmd)

%% AP Correction
cmd = ['"' fullfile(N4Path,'+Seg','N4BiasFieldCorrection.exe') '" ' ,...
    '-d 3 -i "' fullfile(tmp_dir,'tmp_N4_Im.nii.gz') '" ',...
    '-s 1 -w "' fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz') '" ',...
    '-c [25,0] -b [1x1x14,3] -t [0.75,0.01,100] ',...
    '-o ["' fullfile(tmp_dir,'tmp_N4_Im.nii.gz"'),',"',fullfile(tmp_dir,'tmp_Bias.nii.gz"]')];
system(cmd)

%% RL Correction
cmd = ['"' fullfile(N4Path,'+Seg','N4BiasFieldCorrection.exe') '" ' ,...
    '-d 3 -i "' fullfile(tmp_dir,'tmp_N4_Im.nii.gz') '" ',...
    '-s 1 -w "' fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz') '" ',...
    '-c [25,0] -b [1x14x1,3] -t [0.75,0.01,100] ',...
    '-o ["' fullfile(tmp_dir,'tmp_N4_Im.nii.gz"'),',"',fullfile(tmp_dir,'tmp_Bias.nii.gz"]')];
system(cmd)

%% HF Correction
cmd = ['"' fullfile(N4Path,'+Seg','N4BiasFieldCorrection.exe') '" ' ,...
    '-d 3 -i "' fullfile(tmp_dir,'tmp_N4_Im.nii.gz') '" ',...
    '-s 1 -w "' fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz') '" ',...
    '-c [25,0] -b [14x1x1,3] -t [0.75,0.01,100] ',...
    '-o ["' fullfile(tmp_dir,'tmp_N4_Im.nii.gz"'),',"',fullfile(tmp_dir,'tmp_Bias.nii.gz"]')];
system(cmd)

%% Final Correction
cmd = ['"' fullfile(N4Path,'+Seg','N4BiasFieldCorrection.exe') '" ' ,...
    '-d 3 -i "' fullfile(tmp_dir,'tmp_N4_Im.nii.gz') '" ',...
    '-s 2 -w "' fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz') '" ',...
    '-c [50,0] -b [4x4x4,3] -t [0.75,0.01,100] ',...
    '-o ["' fullfile(tmp_dir,'tmp_N4_Im.nii.gz"'),',"',fullfile(tmp_dir,'tmp_Bias.nii.gz"]')];
system(cmd)

Image_N4 = niftiread(fullfile(tmp_dir,'tmp_N4_Im.nii.gz'));

delete(fullfile(tmp_dir,'tmp_N4_Im.nii.gz'));
delete(fullfile(tmp_dir,'tmp_Im_4_N4.nii.gz'));
delete(fullfile(tmp_dir,'tmp_Mask_4_N4.nii.gz'));